### ISSUE TITLE
`#[derive(MyFancyDerive!)]` does not work

### ISSUE THREAD

**Issue by JohnTheCoolingFan** [danielhenrymantilla/macro_rules_attribute-rs#11]
It gives a syntax error when trying to use it like that

*I'll do a quick PR to remove this from docs and readme*

**Comment by danielhenrymantilla** [comment]
You need to use the `#[derive]` provided by this crate:

```rs
#[macro_use]
extern crate macro_rules_attribute;

macro_rules! MyFancyDerive { /* … */ }

#[derive(MyFancyDerive!)]
struct Foo { /* … */ }
```

 * [Demo](https://www.rustexplorer.com/b#%2F*%0A%5Bdependencies%5D%0Amacro_rules_attribute.version%20%3D%20%220.1.3%22%0A*%2F%0A%0A%23%5Bmacro_use%5D%0Aextern%20crate%20macro_rules_attribute%3B%0A%0Amacro_rules!%20MyFancyDerive%20%7B(%20%24(%24_%3Att)*%20)%20%3D%3E%20()%7D%0A%0A%23%5Bderive(MyFancyDerive!)%5D%0Astruct%20Foo%20%7B%20%2F*%20%E2%80%A6%20*%2F%20%7D%0A%0Afn%20main()%0A%7B%7D%0A)
