### ISSUE TITLE
Allow "arguments" for macros.

### ISSUE THREAD

**Issue by Kreijstal** [danielhenrymantilla/macro_rules_attribute-rs#14]
For example look at the following code

```rust
enum DashNumber<N> {
    NegInfinity,
    Number(N),
    Infinity,
}
impl<T> DashNumber<T> {}
impl<N: ops::Add<Output = N> + Clone> ops::Add for DashNumber<N> {
    type Output = Self;
    fn add(self, other: Self) -> Self::Output {
        use DashNumber::*;
        match (self, other) {
            (NegInfinity, _) => NegInfinity,
            (_, NegInfinity) => NegInfinity,
            (Infinity, _) => Infinity,
            (_, Infinity) => Infinity,
            (Number(a), Number(b)) => Number(a.clone() + b.clone()),
        }
    }
}
impl<N: ops::Add<Output = N> + Clone> ops::Add<N> for DashNumber<N> {
    type Output = Self;
    fn add(self, other: N) -> Self::Output {
        use DashNumber::*;
        match (self, other) {
            (NegInfinity, _) => NegInfinity,
            (Infinity, _) => Infinity,
            (Number(a), b) => Number(a.clone() + b.clone()),
        }
    }
}
```

I want to derive the AddAssign attribute automatically, for both of these cases. To do so it can be done something like this
```rust
macro_rules! impl_add_assign {
    ($e:ty,$t:ty) => {
        impl<N: ops::Add<Output = N> + Copy> ops::AddAssign<$t> for $e
            where
                $e: ops::Add<$t, Output = Self> + Copy
        {
            fn add_assign(&mut self, other: $t) {
                *self = *self + other;
            }
        }
    };
}

impl_add_assign!(DashNumber<N>,Self);
impl_add_assign!(DashNumber<N>,N);
```
But it would be nicer if it could be added as a parameter of a macro like
 `#[derive(AddAssign!(N,Self))]`

**Comment by danielhenrymantilla** [comment]
While this would technially be possible, I'd like to, for starters, not deviate too much from the standard `derive` syntax. And that syntax uses `derive` helper attributes for this:

```rs
#[derive(AddAssign!)]
#[derive_args(N, Self)]
```

  - implemented as of #15, and part of the `v0.2.0` release

Note that as part of the discussion in #15, another suggested alternative which I think I'll end up implementing, is to use macro-specific names for the attribute helpers:

```rs
#[derive(AddAssign!)]
#[add_assign(N, Self)]
```

it would just require a bit more work than the #15 implementation.

___

Given all this, I'm tempted to close the issue, at least for now; if you have ideas/comments you are still welcome to share them 🙂; and to be completely honest, mid-to-long term I find your suggestion to be the most convenient one (`#[derive()]` attributes are currently incredibly annoying hard for a `macro_rules!` to parse when not in the right order!)
