### ISSUE TITLE
Readme links link to old version, and consequently the crate's main rustdoc page does, too.

### ISSUE THREAD

**Issue by steffahn** [danielhenrymantilla/macro_rules_attribute-rs#6]
E.g. something like
> With this crate’s <code>#[[apply](https://docs.rs/macro_rules_attribute/0.1.0-rc1/macro_rules_attribute/attr.apply.html)]</code> and <code>#[[derive](https://docs.rs/macro_rules_attribute/0.1.0-rc1/macro_rules_attribute/attr.derive.html)]</code> attributes, it is now possible to use `proc_macro_attribute` syntax to apply a `macro_rules!` macro:

links to `docs.rs/macro_rules_attribute/0.1.0-rc1`.

Due to the way the `README` is included in the documentation, the `docs.rs` documentation is affected, too.

I'm not even sure what the most elegant / useful solution here is, especially without duplicating the README, or risking it being outdated again in the future in case one forgets to update all those links manually.

If it *was* duplicated, I would probably use rustdoc-internal links for the rustdoc, and links to `/latest/..` on Github. OTOH, I guess technically, if the manually-update-the-links-every-time route was taken, then pages for old versions on crates.io look better since they wouldn't get the links to latest version, but instead to the matching docs.rs page. Arguably one might want to automate filling in those version numbers, I'm not familiar with potentially existing infrastructure for such tasks.

**Comment by danielhenrymantilla** [comment]
Thanks for reporting this 🙏 feel free to tell me what you think of the approach taken in #7
