### ISSUE TITLE
Add a no-op derive macro that brings attribute "custom" into scope

### ISSUE THREAD

**Issue by nikis05** [danielhenrymantilla/macro_rules_attribute-rs#9]
Motivation:

```rust
use macro_rules_attribute::derive;

#[derive(MyCustomDerive!)]
#[my_custom_derive(foo = "bar")]
struct Foo;
```

This code example is erroneous, since `my_custom_derive` is not in the scope.

Proposed solution:

```rust
use macro_rules_attribute::{derive, CustomAttr};

#[derive(MyCustomDerive!, CustomAttr)]
#[custom(my_custom_derive(foo = "bar"))]
struct Foo;
```

`CustomAttr` is a no-op derive macro that produces an empty token stream, but brings attribute `custom` into scope. `macro_rules` derive can then use said attribute.

**Comment by danielhenrymantilla** [comment]
Implemented by @ModProg in #15, and released in `v0.2.0` 🙂
